<?php /** @var $this W2P */ ?><!DOCTYPE html>
<!--[if IE 7]>
<html class="ie ie7" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8" <?php language_attributes(); ?>>
<![endif]-->
<!--[if !(IE 7) | !(IE 8) ]><!-->
<html <?php language_attributes(); ?>>
<!--<![endif]-->
<head>
    <meta charset="<?php bloginfo( 'charset' ); ?>">
    <meta name="viewport" content="width=device-width">
    <title><?php wp_title( '|', true, 'right' ); ?></title>
    <link rel="profile" href="http://gmpg.org/xfn/11">
    <link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">
	<?php
		$this->stylesheet()->renderSass();
// 		$this->javascript()->append_file('vendor/modernizr-1.7.min',null,false)
// 							->append_file('vendor/jquery.easing-1.3.pack',null,false)
// 							->append_file('vendor/jquery.mousewheel.min',null,false)
// 							->append_file('vendor/jquery.fancybox-1.3.4.pack', null, false)
// 							->append_file('0_script')
// // 							->append_file('1_forms')
// 							->append_file('2_exclude')
// 							->append_file('r_0_forms', 'if lte IE 8')
// 							->render_js();
	?>
</head>
<body>
	<header id="header">
	</header>
	<section id="content">
		<?php echo $this->content ?>
	</section>
	<footer id="footer">
	</footer>
</body>
</html>